name: Test

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup
        uses: actions/setup-java@v6
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: Test
        run: ./gradlew testDebugUnitTest
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: build
          path: |
            **/build/reports/tests/
            **/build/test-results/
